services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - /workspace/frontend/node_modules
      - frontend-dotnpm:/root/.npm

volumes:
  frontend-dotnpm:
