services:

  backend:
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - reverse-proxy

  frontend:
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - reverse-proxy

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse-proxy/nginx/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - 8080:80
